// <auto-generated />
using AppDotacion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDotacion.Migrations
{
    [DbContext(typeof(AppDotacionContext))]
    [Migration("20250428234818_NombreDeLaMigracion")]
    partial class NombreDeLaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDotacion.Models.Dotacion", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ID"));

                    b.Property<string>("Agente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Agente");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Area");

                    b.Property<string>("AreaGestion")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AreaGestion");

                    b.Property<string>("CARGO")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Clasifica_Cargo")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Clasifica_Cargo");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Cliente");

                    b.Property<string>("Comuna")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Comuna");

                    b.Property<byte?>("Contrato")
                        .HasColumnType("tinyint")
                        .HasColumnName("Contrato");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Correo");

                    b.Property<byte?>("DV")
                        .HasColumnType("tinyint")
                        .HasColumnName("DV");

                    b.Property<string>("EstadoCliente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EstadoCliente");

                    b.Property<string>("EstadoInstalacion")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EstadoInstalacion");

                    b.Property<string>("EstadoServicio")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EstadoServicio");

                    b.Property<int?>("Fecha_Baja")
                        .HasColumnType("int")
                        .HasColumnName("Fecha_Baja");

                    b.Property<int?>("Fecha_Ingreso")
                        .HasColumnType("int")
                        .HasColumnName("Fecha_Ingreso");

                    b.Property<string>("Instalacion")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Instalacion");

                    b.Property<int?>("N_Personal")
                        .HasColumnType("int")
                        .HasColumnName("N_Personal");

                    b.Property<string>("Nombre_Call_Center")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Call_Center");

                    b.Property<string>("Nombre_Jefatura")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Jefatura");

                    b.Property<string>("Pais_Call_Center")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pais_Call_Center");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("Proyecto")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Proyecto");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Region");

                    b.Property<string>("Rut_DNI")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_DNI");

                    b.Property<string>("Rut_DNI2")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_DNI2");

                    b.Property<string>("Rut_Ficticio")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rut_Ficticio");

                    b.Property<string>("Segmento")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Segmento");

                    b.Property<string>("Servicio")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Servicio");

                    b.Property<string>("SubSegmento")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubSegmento");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Supervisor");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoServicio");

                    b.Property<string>("Tipos_de_agente")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipos_de_agente");

                    b.Property<string>("Usuarios_RcWeb")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuarios_RcWeb");

                    b.HasKey("ID");

                    b.ToTable("Dotaciones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
